#!/usr/bin/env bash
# script to install nginx web server
apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
echo 'Hello World!' > /var/www/html/index.html
service nginx start