#!/usr/bin/env bash
# script to install nginx web server
apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
chmod 755 /var/www/html
echo 'Hello World!' > /var/www/html/index.html

sed -i 's/^\tlocation \/ {$/\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=cw8tuNZjIf4;\n\t}\n\n\tlocation \/ {/' /etc/nginx/sites-available/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
    service nginx start
else
    service nginx restart
fi