#!/usr/bin/env bash
# configure nginx to add a custom header to HTTP response
apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
chmod 755 /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=cw8tuNZjIf4;
   }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}" > /etc/nginx/sites-available/default

sed -i "s/# server_tokens off;/server_tokens off;\n\tadd_header X-Served-By \$hostname;/g" /etc/nginx/nginx.conf

service nginx start
