#!/usr/bin/env bash
# setup laod balancer with haproxy
apt-get update
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 426076-web-01 100.26.49.67:80 check
    server 426076-web-02 34.201.61.34:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start