#!/usr/bin/env bash
# Display To infinity and beyond indefinitely
# and is invincible to sigterm signal

while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
