#!/usr/bin/env bash
# This script is displaying "Best School"
# and display hi if the itteration is 9
i=0
while [ $i -lt 10 ]; do
	if [ $i -eq 9 ]; then
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
