#!/usr/bin/env bash
# This script is displaying 1 - 10
# bad luck if the number is 4 and good luck
# if the number is 8
i=1
while [ $i -le 10 ]; do
	if [[ $i -eq 4 ]]; then
		echo "bad luck"
	elif [[ $i -eq 8 ]]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
